---
output:
  pdf_document: default
urlcolor: blue
---

## Week 9

**Topic curated:** Factors affecting follower counts for K-pop celebrities

I want to study how K-pop idols have made use of these restrictions to create their usernames, and from that, how the designs of their usernames might have affected their follower counts, alongside the influence of external factors, like gender, age, and years in the industry.

I will ultimately deduce what characteristics are more likely to attract higher numbers of followers, and along with this data story create a web app on Shiny that lets one create a fake idol profile with a few chosen characteristics and generate an predicted amount of followers.

**Data sources:**

1.  "Kpop Idol Instagram Followers" retrieved from: [Faisal Amir on Kaggle](https://www.kaggle.com/datasets/faisalamir/kpop-idol-followers)
2.  News articles and other sources that help me categorise data - eg. in assessing the size of idols' company and how this affects data: [Who runs K-pop? Big Hit, backers of BTS, Kakao, label of IU, and CJ ENM, with Mnet music channel, loosen grip of 'Big Three' SM, JYP and YG](https://www.scmp.com/lifestyle/k-pop/news/article/3120731/who-runs-k-pop-big-hit-backers-bts-kakao-label-iu-and-cj-enm)

------------------------------------------------------------------------

## Week 10

-   What does it take for a successful Instagram account in the K-pop industry?

-   K-pop might be one of the only music industries where one's Instagram page is almost as important as the music, being an important platform for fan communication, brand ambassadorship, and self-promotion. One's username, a handle that has to be searched to access an Instagram page, is therefore one of the most critical parts of an idol's persona and a significant determinant in the amount of fame and fans they have. Studying the patterns in idols' usernames, as well as other characteristics that can impact one's Instagram followers, is an critical part of social media management, another up-and-coming industry that, as Communications majors, we should keep our eyes on. Being able to decipher the factors behind something as volatile, unpredictable, but also as lucrative as social media fame is especially valuable information in the reputation economy that the world runs on today.

-   Columns: Stage.name, Group, ig_name, Followers, Gender.x, Date.of.Birth, Company, Country

-   Rows: All, excluding outliers in quantity of Followers (based on box plot)
